#!/usr/bin/env python3
"""
Scan the repository for files that contain likely AI-generated markers, then POST them to the configured endpoint.

Environment variables:
- AI_PUSH_ENDPOINT: endpoint to POST to. Defaults to http://localhost:8000/api/push
- AI_HOOK_FAIL_BLOCK: if set to '1' (or 'true'), the script exits non-zero on failure which will block push.

This script is intended to be run from the git repo root (e.g. via a pre-push hook).
"""

import os
import sys
import json
import re
import subprocess
from pathlib import Path
import requests

KEYWORDS = [
    "generated by",
    "ai-generated",
    "ai_generated",
    "generated with",
    "copilot",
    "openai",
    "chatgpt",
    "assistant",
]

MAX_FILE_BYTES = 100 * 1024  # read up to 100KB per file


def repo_root():
    # If the script lives in website/, parents[1] is repository root
    return Path(__file__).resolve().parents[1]


def git_repo_info(path):
    # try to get origin url and current branch
    try:
        origin = subprocess.check_output(["git", "remote", "get-url", "origin"], cwd=path, stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        origin = ""
    try:
        branch = subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=path, stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        branch = ""
    return origin, branch


def is_text_file(p: Path):
    # heuristic: ignore binary files by attempting to decode
    try:
        with open(p, "rb") as f:
            chunk = f.read(4096)
            if b"\x00" in chunk:
                return False
    except Exception:
        return False
    return True


def scan_for_ai(root: Path):
    results = []
    for p in root.rglob("*"):
        if p.is_dir():
            # skip .git and website/received
            if p.match(".git") or "/.git/" in str(p):
                continue
            continue
        if ".git" in p.parts:
            continue
        # skip the website received dir
        if any(part == "received" for part in p.parts):
            continue
        # small heuristic to skip large binaries
        if p.stat().st_size > 200 * 1024:
            continue
        if not is_text_file(p):
            continue
        try:
            raw = p.read_bytes()[:MAX_FILE_BYTES]
            text = None
            try:
                text = raw.decode("utf-8")
            except Exception:
                try:
                    text = raw.decode("latin-1")
                except Exception:
                    continue
            lower = text.lower()
            if any(k in lower for k in KEYWORDS):
                snippet = text[:8000]
                results.append({
                    "path": str(p.relative_to(root)),
                    "size": p.stat().st_size,
                    "snippet": snippet
                })
        except Exception:
            continue
    return results


def main():
    endpoint = os.environ.get("AI_PUSH_ENDPOINT", "http://localhost:8000/api/push")
    block_on_fail = os.environ.get("AI_HOOK_FAIL_BLOCK", "0").lower() in ("1", "true", "yes")

    root = repo_root()
    origin, branch = git_repo_info(root)

    ai_files = scan_for_ai(root)

    payload = {
        "origin": origin,
        "branch": branch,
        "ai_files": ai_files,
    }

    # If there are no AI files, still POST an empty report (optional)
    try:
        r = requests.post(endpoint, json=payload, timeout=10)
        if r.status_code >= 200 and r.status_code < 300:
            print(f"[scan_ai] sent {len(ai_files)} AI-related files to {endpoint}")
            sys.exit(0)
        else:
            print(f"[scan_ai] POST failed: status={r.status_code} body={r.text}")
            if block_on_fail:
                sys.exit(2)
            sys.exit(0)
    except Exception as e:
        print(f"[scan_ai] error sending to endpoint {endpoint}: {e}")
        if block_on_fail:
            sys.exit(2)
        sys.exit(0)


if __name__ == "__main__":
    main()
